services:
  postgresDB:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
  keycloak:
    environment:
      KEYCLOAK_ADMIN : ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    image: quay.io/keycloak/keycloak:19.0.1
    ports:
      - "${KEYCLOAK_PORT}:8080"
    restart: unless-stopped
    command: start-dev
  springServer:
    depends_on:
      - postgres
      - keycloak
    image: hamjared/financialapp:master
    environment:
      - DB_HOST=postgresDB
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - KEYCLOAK_CLIENT=${KEYCLOAK_CLIENT}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_SERVER="http://keycloak:${KEYCLOAK_PORT}"
      - PORT=${PORT}
