name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: finance-webserver

    steps:
    - uses: actions/checkout@v3
    - name: Chmod gradlew
      run: chmod +x ./gradlew
    - name: Build the Jar
      run: ./gradlew build
    - name: ls
      run: ls -la
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg JAR_FILE=build/libs/\*.jar --tag hamjared/financialapp:master
    - name: Login to Docker Hub
      run: docker login -u="hamjared" -p=${{ secrets.DOCKER_HUB }}
    - name: Push the Docker image
      run: docker push hamjared/financialapp:master
      
      
